# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -ldflags "-X github.com/noqqe/veilig/src/serra.Version=`git describe --tags`"  -v veilig.go
    sources:
      - "src/veilig/**/*.go"
      - "veilig.go"
    generates:
      - "./veilig"

  release:
    interactive: true 
    cmds:
      - git tag | tail -5
      - read -p "Version v1.1.1 " version ; git tag $version
      - git push --tags
      - goreleaser release --clean

  default:
    cmds:
      - task: build

