# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -ldflags "-X github.com/noqqe/veilig/src/veilig.Version=`git describe --tags`" -v -o veilig main.go 
    sources:
      - "src/veilig/**/*.go"
      - "main.go"
    generates:
      - "./veilig"

  release:
    interactive: true 
    cmds:
      - git tag | tail -5
      - read -p "Version v1.1.1 " version ; git tag $version
      - git push --tags
      - goreleaser release --clean

  test:
    interactive: true
    deps: 
      - build
    dir: test
    cmds:
      - ../veilig certificates/doesnotexist.crt 1>/dev/null || true 
      - ../veilig certificates/expired.crt 1>/dev/null
      - ../veilig certificates/valid.crt 1>/dev/null
      - ../veilig heise.de 1>/dev/null || true
      - ../veilig https://heise.de 1>/dev/null || true
      - ../veilig 127.0.0.1:7443 1>/dev/null
      - ../veilig 127.0.0.1:8443 1>/dev/null
      - ../veilig https://127.0.0.1:7443 1>/dev/null
      - ../veilig https://127.0.0.1:8443 1>/dev/null
  
  
      


  default:
    cmds:
      - task: build

